server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_gidro
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver


  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


#logging:
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss:SSS} - %msg%n"
#  file:
#    name: app.log
#    max-history: 365
#  level:
#    org.springframework.web: ERROR
#    org.hibernate: ERROR



app:
  run-type: default     #refresh || update
  admin:
    reservoir: akhangaran
    username: akhangaran
    password: akhangaran
    firstName: Akhangaran
    lastName: Akhangaran
    secret-key: g3fXbUlLCV
    files:
      piezometers: "C:/Users/Администратор/Desktop/app/devices/piezometers.csv"
      water-level-gauges: "C:/Users/Администратор/Desktop/app/devices/waterlevelgauges.csv"
      water-level-in-volume: "C:/Users/Администратор/Desktop/app/devices/waterlevelinvolume.csv"
      water-flow-meters: "C:/Users/Администратор/Desktop/app/devices/waterflowmeters.csv"
      hydrological-stations: "C:/Users/Администратор/Desktop/app/devices/hydrologicalstations.csv"
      spillways: "/Users/mirolim/Desktop/Fidrotexm/spillways/spillways.csv"
      dam-body-devices: "/Users/mirolim/Desktop/Fidrotexm/dambodydevices/dambodydevices.csv"
      safety-criteria: "/Users/mirolim/Desktop/Fidrotexm/safety-criteria/safety-criteria.csv"
      crack-gauge: "/Users/mirolim/Desktop/Fidrotexm/crackgauges/crackgauges.csv"
      plumb: "/Users/mirolim/Desktop/Fidrotexm/plumbs/plumbs.csv"
      tiltmeters: "/Users/mirolim/Desktop/Fidrotexm/tiltmeters/tiltmeters.csv"
      deformometers: "/Users/mirolim/Desktop/Fidrotexm/deformometers/deformometers.csv"
    upload:
     folder: "C:/Users/Администратор/Desktop/app/files"
  dispechr:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Xisorak/ftp/dispechr"
  kzr_tunel:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Xisorak/ftp/krz_tunel"
  sempatern_tunell:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Xisorak/ftp/Sempatern_tunell"
  vw:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Xisorak/ftp/greben_gateway/vw"
  anl4:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Xisorak/ftp/greben_gateway/anl4"
  anl1:
      folder: "/home/gidrotech/ftp/Xisorak/greben_gateway/anl1/"
  akhangaran:
    folder: "C:/ftp/akhangaran"
  omnialog_795:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Andijan/ftp/omnialog_795"
  omnialog_804_12_seksiya:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Andijan/ftp/omnialog_804_12_seksiya"
  omnialog_804_24_seksiya:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Andijan/ftp/omnialog_804_24_seksiya"
  omnialog_817_chap:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Andijan/ftp/omnialog_817_chap"
  omnialog_817_ong:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Andijan/ftp/omnialog_817_ong"
  gateway_bosimsiz:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Andijan/ftp/gateway/bosimsiz"
  omnialog_885_shelemer:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Andijan/ftp/omnialog_885_shelemer"
  omnialog_845_atves:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Andijan/ftp/omnialog_845_atves"
  t_1000:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Andijan/ftp/gateway/T-1000"
  tiltmeters:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Andijan/ftp/gateway/Tiltmeters"
  omnialog_804_28_seksiya:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Andijan/ftp/omnialog_804_28_seksiya"
  gateway_bosimsiz_charvak:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Charvak/ftp/gateway/bosimsiz"
  gateway_vodosliv_charvak:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Charvak/ftp/gateway/Vodosliv"
  tasmali_drenaj:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Charvak/ftp/Tasmali_drenaj"
  transportni_sh:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Charvak/ftp/Transportni_sh"
  shtolniya_1:
    folder: "/Users/mirolim/Desktop/Fidrotexm/Charvak/ftp/1-shtolniya"

jwt:
  access:
    key: e4d108799a492f0984189c3743c50dfdbed2f1d3290b28664e323c41fd5e3827
    expiration-time: 86400000
  refresh:
    key: d04d00b0de300a673cc328778fcab74141f063bea03a213e5ba2858d9fe43864
    expiration-time: 172800000


base:
 url: http://10.151.170.10:8080

