package com.example.appgidritexmonitoring.entity.enums;

public enum DeviceDatasourceEnum {
    DISPECHR,
    KRZ_TUNEL,
    SEMPATERN_TUNELL,
    VW,
    ANL1,
    ANL4,
    AKHANGARAN,
    OMNIALOG_795,
    OMNIALOG_817_ONG,
    OMNIALOG_817_CHAP,
    OMNIALOG_804_12_SEKSIYA,
    OMNIALOG_804_24_SEKSIYA,
    GATEWAY_BOSIMSIZ,
    OMNIALOG_885_SHELEMER,
    OMNIALOG_845_ATVES,
    T_1000,
    TILTMETERS,
    OMNIALOG_804_28_SEKSIYA,
    CHARVAK_GATEWAY_BOSIMSIZ,
    TASMALI_DRENAJ,
    TRANSPORTNI_SH,
    SHTOLNIYA_1,
    CHARVAK_GATEWAY_VODOSLIV;

}
