package com.example.appgidritexmonitoring.util;

import com.example.appgidritexmonitoring.payload.ErrorData;
import com.example.appgidritexmonitoring.payload.UserDTO;

import java.util.List;

public interface MessageConstants {
    String YOU_HAVE_NOT_PERMISSION = "YOU_HAVE_NOT_PERMISSION";
    String MUST_NOT_BE_BLANK_USERNAME = "MUST_NOT_BE_BLANK_USERNAME";
    String MUST_NOT_BE_BLANK_PASSWORD = "MUST_NOT_BE_BLANK_PASSWORD";
    String USERNAME_IS_ALREADY_EXISTS = "USERNAME_IS_ALREADY_EXISTS";

    String GATE_NOT_FOUND = "GATE_NOT_FOUND";
    String GATES_NOT_FOUND = "GATES_NOT_FOUND";
    String RESERVOIRS_NOT_FOUND = "RESERVOIRS_NOT_FOUND";
    String RESERVOIR_NOT_FOUND = "RESERVOIR_NOT_FOUND";
    String ROLE_NOT_FOUND = "ROLE_NOT_FOUND";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String TOKEN_INVALID = "TOKEN_INVALID";
    String USER_NOT_FOUND_OR_DISABLED = "USER_NOT_FOUND_OR_DISABLED";
    String LOGIN_OR_PASSWORD_ERROR = "LOGIN_OR_PASSWORD_ERROR";
    String SUCCESSFULLY_TOKEN_GENERATED = "SUCCESSFULLY_TOKEN_GENERATED";
    String USER_PERMISSION_RESTRICTION = "USER_PERMISSION_RESTRICTION";
    String REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED";
    String MUST_NOT_BE_BLANK_FIRST_NAME = "MUST_NOT_BE_BLANK_FIRST_NAME";
    String MUST_NOT_BE_BLANK_LAST_NAME = "MUST_NOT_BE_BLANK_LAST_NAME";
    String MUST_NOT_BE_NULL_ROLE_ID = "MUST_NOT_BE_NULL_ROLE_ID";
    String MUST_NOT_BE_NULL_ATTACHMENT_ID = "MUST_NOT_BE_NULL_ATTACHMENT_ID";


    String SUCCESSFULLY_DELETED = "SUCCESSFULLY_DELETED";
    String SUCCESSFULLY_CHANGED = "SUCCESSFULLY_CHANGED";
    String OBJECT_NOT_VALID = "OBJECT_NOT_VALID";
    String FILE_NAME_INVALID = "FILE_NAME_INVALID";
    String DIRECTORY_NOT_CREATED = "DIRECTORY_NOT_CREATED";
    String FILE_NOT_SAVED = "FILE_NOT_SAVED";
    String ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND";
    String OBJECT_IS_EMPTY = "OBJECT_IS_EMPTY";
    String OBJECT_NOT_FOUNT = "OBJECT_NOT_FOUNT";
    String PAGE_IS_ALREADY_EXISTS = "PAGE_IS_ALREADY_EXISTS";
    String MUST_NOT_BE_BLANK_NAME = "MUST_NOT_BE_BLANK_NAME";
    String MUST_NOT_BE_BLANK_URL_OF_PAGE = "MUST_NOT_BE_BLANK_URL_OF_PAGE";
    String INVALID_FILE_EXTENSION = "INVALID_FILE_EXTENSION";
    String OUT_OF_MAX_FILE_SIZE = "OUT_OF_MAX_FILE_SIZE";
    String NO_DATA = "NO_DATA";


    String INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT";
    String SPILLWAY_NOT_FOUND = "SPILLWAY_NOT_FOUND";
    String WATER_LEVEL_GAUGE_NOT_FOUND = "WATER_LEVEL_GAUGE_NOT_FOUND";
    String PIEZOMETER_NOT_FOUND = "PIEZOMETER_NOT_FOUND";
    String START_DATE_MUST_BE_BEFORE_END_DATE = "START_DATE_MUST_BE_BEFORE_END_DATE";
    String USER_MUST_HAVE_MIN_ONE_RESERVOIR = "USER_MUST_HAVE_MIN_ONE_RESERVOIR";
    String INVALID_DEVICE_TYPE_FORMAT = "INVALID_DEVICE_TYPE_FORMAT";

    String SAFETY_CRITERIA_NOT_FOUND_WITH_ID = "SAFETY_CRITERIA_NOT_FOUND_WITH_ID";


    String SECRET_KEY_INVALID = "SECRET_KEY_INVALID";
    String GROUP_HAS_DOCUMENTS = "GROUP_HAS_DOCUMENTS";
    String MUST_NOT_BE_BLANK_DESC = "MUST_NOT_BE_BLANK_DESC";
}
